rule_01:
  feature: total_usage_mb
  upper_limit: 575.610489
  points: 15

rule_02:
  feature: total_download_mb
  upper_limit: 378.046620
  points: 10

rule_03:
  feature: total_upload_mb
  upper_limit: 158.931903
  points: 10

rule_04:
  feature: avg_usage_mb
  upper_limit: 127.762145
  points: 20

rule_05:
  feature: max_usage_mb
  upper_limit: 252.694410
  points: 25

rule_06:
  feature: Number_of_sessions
  upper_limit: 14.5
  points: 15

rule_07:
  feature: upload_ratio
  upper_limit: 5.144918
  points: 5

# rule_08:
#   minimum_algorithms: 3
#   points: 15

max_raw_score: 115